### ISSUE TITLE
when i run main.go it dosn't work

### ISSUE THREAD

**Issue by ghost** [unixpickle/build.js#1]
this is what happens 
$ go run main.go 
 command-line-arguments
./main.go:26: undefined: CommentOut
./main.go:37: undefined: CommentOut
./main.go:43: undefined: IndentCode
./main.go:47: undefined: IndentCode
./main.go:51: undefined: ScriptFile
./main.go:54: undefined: ReadScriptFile
./main.go:58: undefined: NewDepGraph
./main.go:70: undefined: IndentCode
./main.go:75: undefined: CleanEmptyLines
./main.go:88: undefined: IfStatement
./main.go:88: too many errors

**Comment by unixpickle** [comment]
You run this using `go run *.go`, not `go run main.go`.

**Comment by ghost** [comment]
ok thanks
